export * from "./NavBar"
export * from "./Slider"
export * from "./MainContainer"
export * from "./Aside"
export * from "./Tema1"
export * from "./TituloPrincipal"
export * from "./Figure"
export * from "./Subtitulo"
export * from "./Tema2"
export * from "./Lista"
export * from "./Footer"
export * from "./Collage"
export * from "./ListaDeCotejo"
export * from "./Tema3"
export * from "./Encuesta"
export * from "./Entrevista"


